services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=apipassword
      - POSTGRES_DB=grocerydelivery
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data/

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data: